language: crystal
crystal:
  - latest
services:
  - docker
before_deploy:
  - mkdir bin
  - echo -e 'require "llvm/lib_llvm"\nrequire "llvm/enums"\n' >> src/haste.cr
  - docker run --rm -it -v $PWD:/haste-client -w /haste-client jrei/crystal-alpine crystal build src/haste.cr --static --release --stats --progress -o bin/haste
  - tar -zcvf haste-client-$TRAVIS_TAG-linux-x86_64.tar.gz bin/haste
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: haste-client-$TRAVIS_TAG-linux-x86_64.tar.gz
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    on_success: never
    on_failure: always
