language: crystal
crystal:
  - latest
before_deploy:
  - mkdir bin
  - crystal build src/haste.cr --release --stats --progress --static --no-debug -o bin/haste
  - tar -zcvf haste-client-$TRAVIS_TAG-linux-x86_64.tar.gz bin/haste
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: haste-client-$TRAVIS_TAG-linux-x86_64.tar.gz
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    on_success: never
    on_failure: always
